/**
 * @fileoverview gRPC-Web generated client stub for greeter
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: proto/greeter.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_greeter_pb from '../proto/greeter_pb';


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/greeter.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    proto_greeter_pb.HelloReq,
    proto_greeter_pb.HelloResp,
    (request: proto_greeter_pb.HelloReq) => {
      return request.serializeBinary();
    },
    proto_greeter_pb.HelloResp.deserializeBinary
  );

  sayHello(
    request: proto_greeter_pb.HelloReq,
    metadata: grpcWeb.Metadata | null): Promise<proto_greeter_pb.HelloResp>;

  sayHello(
    request: proto_greeter_pb.HelloReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_greeter_pb.HelloResp) => void): grpcWeb.ClientReadableStream<proto_greeter_pb.HelloResp>;

  sayHello(
    request: proto_greeter_pb.HelloReq,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_greeter_pb.HelloResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greeter.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greeter.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

}

